spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  data:
    mongodb:
      host: mongo
keycloak:
  enabled: true
  realm: tindeer
  auth-server-url: http://keycloak:8080/auth
  ssl-required: external
  resource: tindeer
  principal-attribute: preferred_username
